### ISSUE TITLE
Any way a more than x monsters on screen function can be added for offensive flasks?

### ISSUE THREAD

**Issue by Nevalopo** [Xcesius/AutoFlaskManager#16]
Running as Pathfider i can pretty much always have my flasks up it would be nice if there was a way to have flasks active whenever there are more than x monsters on the screen. There is no way to use flasks like onslaught or diamond flasks atm without taking damage which u barley ever do as a fast pathfinder clearspeed build

**Comment by zaafar** [comment]
@Nevalopo check the latest update. It's not what you asked but it's good for pathfinder builds.
Now you can pop (offensive) flasks based on your skill use. Let me know if this solve your issue.

**Comment by Nevalopo** [comment]
It kinda works. But running something like CI Pathfinder Ngamahu even if i put it at 100% and use on skill use it only uses when u press cyclone and u kinda hold it down all the time. It's good for now tho thanks for the update.
