### ISSUE TITLE
Atziri's promise being spammed instead of waiting for buff duration to end.

### ISSUE THREAD

**Issue by Cicida** [Xcesius/AutoFlaskManager#31]
Title, I think something similar happened with others.

**Comment by zaafar** [comment]
Did u set the delay to the 5000?

**Comment by Cicida** [comment]
Yes, I'm using 3 (for leech) and all of them are used at the same time.
I tried turning off "drink on right click" but it does the same thing when it is based on hp or skill use.
If there's some sort of log I can give you it might give you a better idea of what is happening.

**Comment by zaafar** [comment]
Turn off "drink all flask together"
